#!/bin/sh
#
# @name Hexacopter
#
# @type Coaxial Trirotor
#
# @maintainer Lachlan Orr <lachlan.orr15@imperial.ac.uk>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MPC_THR_HOVER 40.0

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX 0.2021534554521046
param set-default CA_ROTOR0_PY 0.3509401379847765
param set-default CA_ROTOR0_KM  -0.06

param set-default CA_ROTOR1_PX 0.2021534554521046
param set-default CA_ROTOR1_PY 0.3509401379847765
param set-default CA_ROTOR1_KM 0.06

param set-default CA_ROTOR2_PX -0.40499992887425096
param set-default CA_ROTOR2_PY 0.0
param set-default CA_ROTOR2_KM -0.06

param set-default CA_ROTOR3_PX -0.40499992887425096
param set-default CA_ROTOR3_PY 0.0
param set-default CA_ROTOR3_KM 0.06

param set-default CA_ROTOR4_PX 0.2025692852118133
param set-default CA_ROTOR4_PY -0.3507002775715683
param set-default CA_ROTOR4_KM -0.06

param set-default CA_ROTOR5_PX 0.2025692852118133
param set-default CA_ROTOR5_PY -0.3507002775715683
param set-default CA_ROTOR5_KM 0.06

param set-default SYS_AUTOCONFIG 1

param set-default MAV_TYPE 13

param set-default MC_PITCHRATE_K 1.000
param set-default MC_PITCHRATE_I 0.28
param set-default MC_PITCHRATE_D 0.0005

param set-default MC_ROLLRATE_K 1.000
param set-default MC_ROLLRATE_I 0.28
param set-default MC_ROLLRATE_D 0.0005

param set-default MC_YAWRATE_K 1.0
param set-default MC_YAWRATE_I 0.17

param set-default MC_PITCH_P 4.5
param set-default MC_ROLL_P 4.5
param set-default MC_YAW_P 5

param set-default MPC_XY_VEL_P_ACC 2.2
param set-default MPC_XY_VEL_I_ACC 0.1
param set-default MPC_XY_VEL_D_ACC 0.2
param set-default MPC_Z_VEL_P_ACC 8.0
param set-default MPC_Z_VEL_I_ACC 0.2
param set-default MPC_Z_VEL_D_ACC 0.2

param set-default MPC_XY_P 0.55
param set-default MPC_Z_P 2.0

param set-default MPC_TILTMAX_AIR 20.0
param set-default MC_YAWRATE_MAX 45.0

param set-default BAT1_N_CELLS 6

param set-default IMU_GYRO_CUTOFF 40
param set-default IMU_DGYRO_CUTOFF 40

param set-default MC_AIRMODE 1



# set MIXER hexa_cox

# set PWM_OUT 123456
